---
title: "visualization"
subtitle: " Part 2"
author: "linshan"
date: "2024-09-26"
output: github_document
---
```{r setup}
library(tidyverse)
library(patchwork)
```

## Load the data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## remember this plot?
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
##散点图
    geom_point(alpha = .5)
```

## Labels
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017."
    ##caption 是注释
  )
```

## Scales

Starts with the same plot
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c("-15 C","0 C","15C")
  ) +
  scale_y_continuous(
    trans = "sqrt",  #或者log。。
    position = "right" #把轴放到右边。。
  )
```

Look at color scales
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  scale_color_hue(
    name = "Location",
    h = c(100,300))
```

##另一个方法
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  )
```

## Themes

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  theme(legend.position = "bottom")
#感觉像是把图例放到图的底部
```

Change the overall theme
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  theme_bw() #把背景换成白色，黑色边框
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  theme_minimal() #把背景换成白色，但没有黑色边框
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  theme_classic() #把背景换成白色(无网格），没有黑色边框
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily tempreture(C)",
    y = "Maximum daily tempreture(C)",
    caption = "Data from rnova package;tempretures in 2017.") +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  ggthemes::theme_excel() +
  theme(legend.position = "bottom") +
  theme(legend.position = "bottom")
#如果想同时改变theme主题和其他东西like legend，需要将legend改变后置于theme主题改变之后
```

## Setting options

```{r eval = FALSE}
#一般画图的操作：预先设定好自己喜欢的theme和color
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```









